---
javascripts:
- base:
  - jquery
  - application
- home:
  - home
- search:
  - search
  - jquery 
  - jquery.fancybox
  - jquery.ui
- conflict:
  - conflict

stylesheets:
- base:
  - application
  - jquery.fancybox
  - jquery.ui
- home:
  - home
- search:
  - search
- conflict:
  - conflict