---
javascripts:
- base:
  - jquery/jquery
  - jquery/jquery.tmpl
  - jquery/jquery.utils
  - jquery/jquery.formatter
  - jquery/jquery.fancybox
  - jquery/jquery.ui
  - application
- home:
  - home
- search:
  - search
- conflict:
  - conflict
  - jquery/jquery.amzcart

stylesheets:
- base:
  - application
  - jquery.fancybox
  - jquery.ui
- home:
  - home
- search:
  - search
- conflict:
  - conflict
