---
javascripts:
- base:
  - jquery/jquery
  - jquery/jquery.tmpl
  - jquery/jquery.utils
  - jquery/jquery.formatter
  - jquery/jquery.fancybox
  - jquery/jquery.ui
  - jquery/jquery.scrollTo
  - jquery/jquery.randombg
  - application
- home:
  - home
- search:
  - search
- conflict:
  - conflict
- conflict_wrapper:
  - conflict_wrapper

stylesheets:
- base:
  - application
  - jquery.fancybox
  - jquery.ui
- home:
  - home
- search:
  - search
- conflict:
  - conflict
- user:
  - scaffold
