---
javascripts:
- base:
  - jquery/jquery
  - jquery/jquery.tmpl
  - jquery/jquery.utils
  - jquery/jquery.formatter
  - jquery/jquery.fancybox
  - jquery/jquery.ui
  - jquery/jquery.scrollTo
  - jquery/jquery.randombg
  - jquery/jquery.autocomplete
  - application
- home:
  - backgroundChanger
  - home
- search:
  - backgroundChanger
  - search
- conflict:
  - conflict
- help:
  - backgroundChanger
- about:
  - backgroundChanger
- user:
  - backgroundChanger
- recipe:
  - backgroundChanger
  - recipe

stylesheets:
- base:
  - application
  - jquery.fancybox
  - jquery.ui
  - jquery.autocomplete
- home:
  - home
- search:
  - search
- conflict:
  - conflict
- user:
  - scaffold
- recipe:
  - recipe
- help:
  - help
- about:
  - about